"""Icons come from a stand of the CI (CI ABGLEICH WG-Z1, Etappe 3).

static/icons.js is written by scripts/ci/icons_erzeugen.py from the CI's
marke/icons/ui/ at a stand ci-YY.M.n, never from main. CI names (li('kosten'))
and the Lucide names Wings' code calls (li('folder'), TAFEL in the script) are
both keys of LI_PATHS. Stroke is the CI's fixed 1.5: no call passes its own.

With a copy of aimighty-ci at AIMIGHTY_CI, the file is compared byte by byte
with what the generator writes from the stand it names.

Run:
    ./scripts/test.sh tests/test_ci_zeichen.py -v
"""

import os
import pathlib
import re
import subprocess
import sys

import pytest

REPO = pathlib.Path(__file__).parent.parent
sys.path.insert(0, str(REPO / "scripts" / "ci"))
import icons_erzeugen  # noqa: E402

ICONS = (REPO / "static" / "icons.js").read_text(encoding="utf-8")
STAND = re.search(r"const LI_STAND = '([^']+)';", ICONS)


def test_icons_come_from_a_stand_not_main():
    assert "GENERATED by scripts/ci/icons_erzeugen.py" in ICONS
    assert STAND and re.fullmatch(r"ci-\d{2}\.\d{1,2}\.\d+", STAND.group(1)), "icons.js names no stand"


def test_every_lucide_name_wings_calls_points_at_a_ci_icon():
    schluessel = set(re.findall(r"^  '([\w-]+)':", ICONS, re.M))
    assert set(icons_erzeugen.TAFEL) <= schluessel
    assert set(icons_erzeugen.TAFEL.values()) <= schluessel


def test_stroke_is_the_ci_one():
    assert "function li(name, size = 16, stroke = 1.5)" in ICONS
    eigene = []
    for datei in (REPO / "static").glob("*.js"):
        for m in re.finditer(r"\bli\(\s*[^()]*?,\s*\d+\s*,\s*[\d.]+\s*\)", datei.read_text(encoding="utf-8")):
            eigene.append(f"{datei.name}: {m.group(0)}")
    assert eigene == [], eigene


@pytest.mark.skipif(not os.environ.get("AIMIGHTY_CI"), reason="AIMIGHTY_CI (a copy of aimighty-ci) not set")
def test_icons_js_equals_the_generator_output():
    out = subprocess.run([sys.executable, str(REPO / "scripts" / "ci" / "icons_erzeugen.py"),
                          "--ci", os.environ["AIMIGHTY_CI"], "--stand", STAND.group(1), "--pruefen"],
                         capture_output=True, text=True)
    assert out.returncode == 0, out.stdout + out.stderr


# ── Inline icons (Etappe 3b) ─────────────────────────────────────────────────
import zeichen_einsetzen  # noqa: E402

# CI names that are not in the stand yet; their <svg> carries data-li-ausstehend.
AUSSTEHEND = {"pause", "erweiterung", "vergroessern", "verkleinern", "vollbild", "einpassen", "warteschlange"}


def _inline_icons():
    for name in zeichen_einsetzen.DATEIEN:
        src = (REPO / "static" / name).read_text(encoding="utf-8")
        for m in re.finditer(r"<svg\b[^>]*>", src):
            if re.search(r"viewBox=.0 0 (24 24|16 16)", m.group(0)):
                yield name, src.count("\n", 0, m.start()) + 1, m.group(0)


def test_every_inline_icon_names_its_ci_icon():
    ohne = [f"{d}:{z}" for d, z, tag in _inline_icons() if "data-li" not in tag]
    assert ohne == [], f"inline <svg> without data-li (a CI name): {ohne}"


def test_inline_icons_are_drawn_from_the_stand():
    out = subprocess.run([sys.executable, str(REPO / "scripts" / "ci" / "zeichen_einsetzen.py"), "--pruefen"],
                         capture_output=True, text=True)
    assert out.returncode == 0, out.stdout + "\nrun: python3 scripts/ci/zeichen_einsetzen.py"


def test_waiting_icons_are_only_those_not_yet_in_the_stand():
    wartend = {re.search(r'data-li-ausstehend="([\w-]+)"', tag).group(1)
               for _, _, tag in _inline_icons() if "data-li-ausstehend" in tag}
    vorhanden = set(re.findall(r"^  '([\w-]+)':", ICONS, re.M))
    assert wartend <= AUSSTEHEND
    assert wartend & vorhanden == set(), f"in the stand now, switch to data-li: {wartend & vorhanden}"
