apiVersion: v1
kind: Service
metadata:
  name: wings
  namespace: {{ .Release.Namespace }}
  labels:
    app: wings
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.webuiPort }}
    targetPort: {{ .Values.webuiPort }}
    protocol: TCP
  selector:
    app: wings
