#!/usr/bin/env python3
"""Writes static/icons.js from a stand of the CI (CI ABGLEICH WG-Z1, Etappe 3).

The icons come from the CI's marke/icons/ui/ at a stand ci-YY.M.n, never from
main. Each CI icon is in LI_PATHS under its CI name (li('kosten')); the Lucide
names Wings' code and upstream ports call (li('folder')) point at the CI icon
of the same meaning through TAFEL below — the only place where Lucide names
stand. Stroke is the CI's fixed 1.5.

    python3 scripts/ci/icons_erzeugen.py --ci ../aimighty-ci --stand ci-26.10.19
    python3 scripts/ci/icons_erzeugen.py --ci ../aimighty-ci --stand ci-26.10.19 --pruefen
"""
import argparse
import pathlib
import re
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent.parent
ZIEL = REPO / "static" / "icons.js"

# Lucide name (as Wings' code calls li()) -> CI name. Decided in ABGLEICH WG-Z1.
TAFEL = {
    "alert-triangle": "achtung", "archive": "datensicherung", "arrow-right": "weiter",
    "arrow-up": "pfeil-hoch", "brain": "gedaechtnis", "calendar": "kalender", "check": "erfolg",
    "chevron-down": "chevron", "chevron-right": "chevron-rechts", "chevron-up": "chevron-hoch",
    "clock": "frist", "copy": "kopieren", "cpu": "grafikeinheit", "database": "datenbank",
    "download": "herunterladen", "external-link": "extern", "eye": "anzeigen", "file-text": "dokumente",
    "folder": "ordner", "globe": "netzrecherche", "grip-vertical": "griff", "image": "bild",
    "lightbulb": "erkenntnis", "link": "verknuepfung", "lock": "schloss", "paperclip": "anhang",
    "pencil": "bearbeiten", "play": "lauf-gestartet", "plus": "plus", "refresh-cw": "neu-laden",
    "save": "speichern", "search": "suche", "settings": "einstellungen", "sparkles": "ai",
    "square": "stopp", "star": "standard", "trash-2": "loeschen", "upload": "hochladen",
    "user": "nutzer", "volume-2": "vorlesen", "wrench": "fertigkeit", "x": "schliessen", "zap": "ereignis",
    # the 21 that had no name (WG-Z1, 10.10.2026)
    "loader": "laden", "rotate-ccw": "wiederholen", "list-todo": "liste", "file-pen": "bearbeiten",
    "file-code": "code", "book-open": "wissensdatenbank", "message-square": "besprechung",
    "terminal": "rolle-konsole", "bot": "ai", "shuffle": "weitergabe", "dollar-sign": "kosten",
    "hash": "anzahl", "git-branch": "zweig", "layers": "zusammenfuehren", "plug": "stecker",
    "undo": "rueckgaengig", "audio-lines": "welle", "braces": "code", "clipboard-list": "liste",
    "map": "kalender",
}

KOPF = """// ── Icons from the AImighty CI (CI ABGLEICH WG-Z1) ──────────────────────────
// GENERATED by scripts/ci/icons_erzeugen.py from stand {stand}: do not edit.
// li('kosten') takes a CI name; li('folder') a Lucide name that upstream ports
// call, which points at the CI icon of the same meaning (TAFEL in the script).
// Usage: li('folder') → a ready-to-embed SVG string; stroke 1.5, currentColor.
// The returned SVG uses display:inline-block + vertical-align so it sits
// neatly beside text in both HTML templates and innerHTML assignments.
const LI_STAND = '{stand}';

const LI_PATHS = {{
"""

FUSS = """}};

/**
 * Returns an SVG string for the given icon name.
 * @param {{string}} name   – key in LI_PATHS: a CI name ('kosten') or a Lucide name ('folder')
 * @param {{number}} size   – width/height in px (default 16)
 * @param {{number|string}} stroke – stroke-width (default 1.5, fixed in the CI)
 * @returns {{string}} SVG element string ready for innerHTML
 */
function li(name, size = 16, stroke = 1.5) {{
  const p = LI_PATHS[name];
  if (!p) {{ console.warn('li(): unknown icon', name); return ''; }}
  return `<svg width="${{size}}" height="${{size}}" viewBox="0 0 24 24" fill="none" `
       + `stroke="currentColor" stroke-width="${{stroke}}" stroke-linecap="round" `
       + `stroke-linejoin="round" aria-hidden="true" `
       + `style="display:inline-block;vertical-align:-0.15em;flex-shrink:0">${{p}}</svg>`;
}}
"""


def _innen(svg):
    m = re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S)
    if not m:
        raise SystemExit("kein <svg> gefunden")
    return m.group(1).strip()


def erzeugen(ci, stand):
    if not re.fullmatch(r"ci-\d{2}\.\d{1,2}\.\d+", stand):
        raise SystemExit(f"{stand}: kein Stand ci-YY.M.n — Wings nimmt nie main")
    liste = subprocess.run(["git", "-C", str(ci), "ls-tree", "--name-only", f"{stand}:marke/icons/ui"],
                           capture_output=True, text=True, check=True).stdout.split()
    ci_icons = {}
    for datei in sorted(liste):
        if datei.endswith(".svg"):
            svg = subprocess.run(["git", "-C", str(ci), "show", f"{stand}:marke/icons/ui/{datei}"],
                                 capture_output=True, text=True, check=True).stdout
            ci_icons[datei[:-4]] = _innen(svg).replace("'", "\\'")
    fehlt = sorted({v for v in TAFEL.values()} - set(ci_icons))
    if fehlt:
        raise SystemExit(f"im Stand {stand} fehlt: {fehlt}")
    zeilen = ["  // CI names"]
    zeilen += [f"  '{n}': '{p}'," for n, p in sorted(ci_icons.items())]
    zeilen.append("  // Lucide names Wings' code calls -> CI icon of the same meaning")
    zeilen += [f"  '{l}': '{ci_icons[c]}',  // {c}" for l, c in sorted(TAFEL.items()) if l not in ci_icons]
    return KOPF.format(stand=stand) + "\n".join(zeilen) + "\n" + FUSS.format()


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--ci", required=True, help="Pfad zu einer Kopie von aimighty-ci (mit Tags)")
    ap.add_argument("--stand", required=True, help="Stand ci-YY.M.n")
    ap.add_argument("--pruefen", action="store_true", help="nur vergleichen, Rückgabe 1 bei Abweichung")
    args = ap.parse_args(argv)
    soll = erzeugen(args.ci, args.stand)
    if args.pruefen:
        gleich = ZIEL.read_text(encoding="utf-8") == soll
        print(f"static/icons.js: {'gleich' if gleich else 'weicht ab von'} Stand {args.stand}")
        return 0 if gleich else 1
    ZIEL.write_text(soll, encoding="utf-8")
    print(f"geschrieben: static/icons.js aus {args.stand}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
